language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
script:
  - coverage run -m pytest tests
after_success:
  - codecov
deploy:
    # TEST provider - deploys to test.pypi.org from pushes to main branch
  - provider: pypi
    username: "__token__"
    distributions: "sdist bdist_wheel"
    server: "https://test.pypi.org/legacy/"
    edge: true
    on:
      branch: main
      python: "3.9"
    # PROD provider - deploys to pypi.org from tag pushes
  - provider: pypi
    username: "__token__"
    distributions: "sdist bdist_wheel"
    edge: true
    on:
      python: "3.9"
      tags: true
