language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
script:
  - coverage run -m pytest tests
after_success:
  - codecov
deploy:
  provider: pypi
  username: "__token__"
  edge: true # opt in to dpl v2
  distributions: "sdist bdist_wheel"
  on:
    all_branches: true
    python: "3.9"
      #tags: true
